language: python

jobs:
  include:
    - os: osx
      osx_image: xcode11.6
      env: URL=https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
      language: generic
    - os: linux
      dist: bionic
      env: URL=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
      python: "3.8"
    - os: linux
      dist: xenial
      env: URL=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
      python: "3.7"
    - os: linux
      dist: bionic
      env: URL=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
      python: "3.6"

before_install:
  - export PYTHON=3.8.5
  - export TRINITY=2.8.5  # The latest version 2.11.0 can't be manually compiled on macOS somehow.
  - export SRA=2.10.8
  - bash ./.travis_before_install.sh $URL
  - |-
      case $TRAVIS_OS_NAME in
        linux)
          export PATH="$PATH:$PWD/miniconda3/bin"
        ;;
        osx)
          export PATH="$PWD/miniconda3/bin:$PWD/trinityrnaseq-Trinity-v${TRINITY}:$PATH"
          export TRINITY_HOME="$PWD/trinityrnaseq-Trinity-v${TRINITY}"
        ;;
      esac
  - echo $(which samtools)
  - echo $(samtools --version)
  - echo $(which Trinity)
  - echo $(Trinity --version)
  - echo $(which fastq-dump)
  - echo $(fastq-dump --version)

install:
  - pip install .[test]

script:
  - travis_wait 20 pytest --cov=r2g
 
after_success:
  - codecov
