name: Run a quick test using Conda

on:
  repository_dispatch:
    types: [trigger-dryrun-conda]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install r2g by Conda ans run a quick test
      env:
        NAME: r2g.dev
        PRIVATE_WEBDRIVER: ${{ secrets.PRIVATE_WEBDRIVER }}
      run : |
        wget -qO miniconda3.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        bash miniconda3.sh -bfp /opt/miniconda3
        /opt/miniconda3/bin/conda config --add channels defaults
        /opt/miniconda3/bin/conda config --add channels bioconda
        /opt/miniconda3/bin/conda config --add channels conda-forge
        /opt/miniconda3/bin/conda install -yq yangwu91/${NAME}
        mkdir -p "${HOME}"/.ncbi
        echo "/LIBS/GUID = \"$(uuidgen)\"" > "${HOME}"/.ncbi/user-settings.mkfg
        /opt/miniconda3/bin/r2g --dry-run
